package com.osp.ucenter.persistence.model;

import java.io.Serializable;

public class UcPermission implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_permission.Permission_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_permission.Permission_Type
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private String permissionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_permission.Menu_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_permission.Permission_id
     *
     * @return the value of uc_permission.Permission_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_permission.Permission_id
     *
     * @param permissionId the value for uc_permission.Permission_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_permission.Permission_Type
     *
     * @return the value of uc_permission.Permission_Type
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_permission.Permission_Type
     *
     * @param permissionType the value for uc_permission.Permission_Type
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_permission.Menu_id
     *
     * @return the value of uc_permission.Menu_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_permission.Menu_id
     *
     * @param menuId the value for uc_permission.Menu_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}