package com.osp.ucenter.persistence.model;

import java.io.Serializable;

public class UcPermissionAction implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_permission_action.Permission_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_permission_action.Action_Id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer actionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_permission_action.Permission_id
     *
     * @return the value of uc_permission_action.Permission_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_permission_action.Permission_id
     *
     * @param permissionId the value for uc_permission_action.Permission_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_permission_action.Action_Id
     *
     * @return the value of uc_permission_action.Action_Id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_permission_action.Action_Id
     *
     * @param actionId the value for uc_permission_action.Action_Id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }
}