package com.osp.ucenter.persistence.model;

import java.io.Serializable;

public class UcRole implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.role_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.role_Name
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role.SystemCode
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private String systemcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.role_id
     *
     * @return the value of uc_role.role_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.role_id
     *
     * @param roleId the value for uc_role.role_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.role_Name
     *
     * @return the value of uc_role.role_Name
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.role_Name
     *
     * @param roleName the value for uc_role.role_Name
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role.SystemCode
     *
     * @return the value of uc_role.SystemCode
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role.SystemCode
     *
     * @param systemcode the value for uc_role.SystemCode
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode == null ? null : systemcode.trim();
    }
}