package com.osp.ucenter.persistence.model;

import java.io.Serializable;

public class UcRolePermission implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role_permission.roleid
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_role_permission.permission
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    private Integer permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role_permission.roleid
     *
     * @return the value of uc_role_permission.roleid
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role_permission.roleid
     *
     * @param roleid the value for uc_role_permission.roleid
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_role_permission.permission
     *
     * @return the value of uc_role_permission.permission
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_role_permission.permission
     *
     * @param permission the value for uc_role_permission.permission
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
}