package com.osp.ucenter.persistence.model;

import java.io.Serializable;

public class UcSystem implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_system.SystemCode
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private String systemcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_system.SystemName
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private String systemname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_system.SystemCode
     *
     * @return the value of uc_system.SystemCode
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public String getSystemcode() {
        return systemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_system.SystemCode
     *
     * @param systemcode the value for uc_system.SystemCode
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setSystemcode(String systemcode) {
        this.systemcode = systemcode == null ? null : systemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_system.SystemName
     *
     * @return the value of uc_system.SystemName
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public String getSystemname() {
        return systemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_system.SystemName
     *
     * @param systemname the value for uc_system.SystemName
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setSystemname(String systemname) {
        this.systemname = systemname == null ? null : systemname.trim();
    }
}