package com.osp.ucenter.persistence.model;

public class UcUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role.user_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_user_role.role_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role.user_id
     *
     * @return the value of uc_user_role.user_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role.user_id
     *
     * @param userId the value for uc_user_role.user_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_user_role.role_id
     *
     * @return the value of uc_user_role.role_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_user_role.role_id
     *
     * @param roleId the value for uc_user_role.role_id
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}