package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcAction;

public interface UcActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int deleteByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    UcAction selectByPrimaryKey(Integer actionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKeySelective(UcAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKey(UcAction record);
}