package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcMenu;

public interface UcMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_menu
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_menu
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_menu
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_menu
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    UcMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_menu
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKeySelective(UcMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_menu
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKey(UcMenu record);
}