package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcPermissionAction;

public interface UcPermissionActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcPermissionAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission_action
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcPermissionAction record);
}