package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcPermission;

public interface UcPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int deleteByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    UcPermission selectByPrimaryKey(Integer permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKeySelective(UcPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_permission
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKey(UcPermission record);
}