package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcRole;

public interface UcRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    UcRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKeySelective(UcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKey(UcRole record);
}