package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcRolePermission;

public interface UcRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role_permission
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    int insert(UcRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_role_permission
     *
     * @mbg.generated Thu Aug 17 11:13:33 CST 2017
     */
    int insertSelective(UcRolePermission record);
}