package com.osp.ucenter.persistence.dao;

import java.util.ArrayList;
import java.util.List;

import com.osp.ucenter.persistence.bo.UcRolePermissionAllocationBo;
import com.osp.ucenter.persistence.model.UcRole;

public interface UcRoleMapper {

	ArrayList<UcRole> selectAllRoles();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table uc_role
	 *
	 * @mbg.generated Wed Aug 09 18:40:44 CST 2017
	 */
	int deleteByPrimaryKey(Integer roleId);
	
	int findCount();
	int insert(UcRole record);

	int insertSelective(UcRole record);

	UcRole selectByPrimaryKey(Integer roleId);

	int updateByPrimaryKeySelective(UcRole record);

	int updateByPrimaryKey(UcRole record);
	
	List<UcRolePermissionAllocationBo> selectPermissionByRoleIds();
}