package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcSystem;

public interface UcSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_system
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int deleteByPrimaryKey(String systemcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_system
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_system
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_system
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    UcSystem selectByPrimaryKey(String systemcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_system
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKeySelective(UcSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_system
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int updateByPrimaryKey(UcSystem record);
}