package com.osp.ucenter.persistence.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.osp.ucenter.persistence.bo.UcRoleBo;
import com.osp.ucenter.persistence.model.UcUser;

public interface UcUserMapper {
	/**
	 * 用户登陆
	 * @param ucUser
	 * @return
	 */
	UcUser login(@Param("username") String username, @Param("password") String password);
	/**
	 * 判断用户是否存在
	 * @param username
	 * @param password
	 * @return
	 */
	UcUser findUser(@Param("userId") Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int insert(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int insertSelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    UcUser selectByPrimaryKey(Integer userId);

    /**
     * 根据用户编号（主键）修改用户信息
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int updateByPrimaryKeySelective(UcUser record);

    int updateByPrimaryKey(UcUser record);
    
	List<UcRoleBo> selectRoleByUserId(@Param("id") Integer id);
}