package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcUserRole;

public interface UcUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insert(UcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user_role
     *
     * @mbg.generated Wed Aug 09 18:40:44 CST 2017
     */
    int insertSelective(UcUserRole record);
}