package com.osp.ucenter.persistence.dao;

import com.osp.ucenter.persistence.model.UcUser;

public interface UcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int insert(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int insertSelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    UcUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int updateByPrimaryKeySelective(UcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_user
     *
     * @mbg.generated Wed Aug 09 18:34:31 CST 2017
     */
    int updateByPrimaryKey(UcUser record);
}